### ISSUE TITLE
Devices aren't recognized

### ISSUE THREAD

**Issue by alexdie** [PatchworkBoy/homebridge-edomoticz#91]
I have four Blind switches set up in Domoticz: 

```
{
   "ActTime" : 1500561169,
   "ServerTime" : "2017-07-20 16:32:49",
   "Sunrise" : "05:38",
   "Sunset" : "21:07",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000042",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-20 15:26:01",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Wohzimmer Tür",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ARC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000042",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-20 15:21:10",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Wohnzimmer Fenster",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ARC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "2"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000042",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-20 15:57:14",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Bad",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ARC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 3,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "3"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000042",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-20 15:57:17",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Schlafzimmer",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ARC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 4,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "4"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}
```

My config.json:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:21:3E:E4:DE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Configuration file for (e)xtended Domoticz platform.",
    "platforms": [
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "192.168.XXX.XXX",
            "port": "8080",
            "ssl": 0,
            "roomid": "2",
            "mqtt": 0
        }
    ],
    "accessories": []
}
```

And the log: 

```
npm info ok
[7/20/2017, 4:15:43 PM] Loaded plugin: homebridge-edomoticz
[7/20/2017, 4:15:43 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
[7/20/2017, 4:15:43 PM] ---
[7/20/2017, 4:15:43 PM] Loaded config.json with 0 accessories and 1 platforms.
[7/20/2017, 4:15:43 PM] ---
[7/20/2017, 4:15:43 PM] Loading 1 platforms...
[7/20/2017, 4:15:43 PM] [eDomoticz] Initializing eDomoticz platform...
[7/20/2017, 4:15:43 PM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
```

I can't figure out what the issue is.  Apologies if this is an obvious error on my end.

**Comment by alexdie** [comment]
Additional information: 
The devices are added to the file /homebridge/accessories/cachedAccessories. 
When restarting homebridge this error occurs:
```
[7/20/2017, 4:41:19 PM] Loaded plugin: homebridge-edomoticz
[7/20/2017, 4:41:19 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
[7/20/2017, 4:41:19 PM] ---
[7/20/2017, 4:41:19 PM] Loaded config.json with 0 accessories and 1 platforms.
[7/20/2017, 4:41:19 PM] ---
[7/20/2017, 4:41:19 PM] Loading 1 platforms...
[7/20/2017, 4:41:19 PM] [eDomoticz] Initializing eDomoticz platform...
[7/20/2017, 4:41:19 PM] Loading 0 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:170
throw new Error(pluginName + " - " + platformName + " attempt to unregister an accessory that isn\'t PlatformAccessory!");

^

Error: homebridge-edomoticz - eDomoticz attempt to unregister an accessory that isn't PlatformAccessory!

at API.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:170:13)
at eDomoticzPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-edomoticz/index.js:176:16)
at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:342:24)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:83:8)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
```

It occurs until the cachedAccessories file is removed.

**Comment by Brklnbnc** [comment]
Same problem here after upgrading the homebridge-eDomoticz plugin to version 2.0.0... I've emptied persist and accessories folder, have deleted my house in Home.app, but it's impossible to connect to my devices.

**Comment by xTheRamon** [comment]
Hey there!

Yeah, it seems you've got a hold of version 2.0. There were still a few bugs present, but I think I have resolved them all in 2.0.5. (I'm using that version at home myself)

Could you try and update to the latest version on npm and see if that resolves your issue?
I'm sorry!

**Comment by alexdie** [comment]
Thanks for the quick response. Unfortunately it still doesn't detect my devices. Here's the startup log of a fresh installation: 

```
npm info lifecycle homebridge-edomoticz@2.0.5~preinstall: homebridge-edomoticz@2.0.5
npm info lifecycle homebridge-edomoticz@2.0.4~preuninstall: homebridge-edomoticz@2.0.4
npm info lifecycle homebridge-edomoticz@2.0.4~uninstall: homebridge-edomoticz@2.0.4
npm info lifecycle homebridge-edomoticz@2.0.4~postuninstall: homebridge-edomoticz@2.0.4
npm info linkStuff homebridge-edomoticz@2.0.5
npm info lifecycle homebridge-edomoticz@2.0.5~install: homebridge-edomoticz@2.0.5
npm info lifecycle homebridge-edomoticz@2.0.5~postinstall: homebridge-edomoticz@2.0.5
/usr/local/lib
`-- homebridge-edomoticz@2.0.5

npm info ok
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info ok
[7/21/2017, 2:00:24 PM] Loaded plugin: homebridge-edomoticz
[7/21/2017, 2:00:24 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
[7/21/2017, 2:00:24 PM] ---
[7/21/2017, 2:00:24 PM] Loaded config.json with 0 accessories and 1 platforms.
[7/21/2017, 2:00:24 PM] ---
[7/21/2017, 2:00:24 PM] Loading 1 platforms...
[7/21/2017, 2:00:24 PM] [eDomoticz] Initializing eDomoticz platform...
[7/21/2017, 2:00:24 PM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

┌────────────┐
│ 031-45-154 │
└────────────┘

[7/21/2017, 2:00:24 PM] Homebridge is running on port 51826.
```

When I restart homebridge after a first run it doesn't crash anymore but throws this error: 

```
[7/21/2017, 2:01:42 PM] Loaded plugin: homebridge-edomoticz
[7/21/2017, 2:01:42 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
[7/21/2017, 2:01:42 PM] ---
[7/21/2017, 2:01:42 PM] Loaded config.json with 0 accessories and 1 platforms.
[7/21/2017, 2:01:42 PM] ---
[7/21/2017, 2:01:42 PM] Loading 1 platforms...
[7/21/2017, 2:01:42 PM] [eDomoticz] Initializing eDomoticz platform...
[7/21/2017, 2:01:42 PM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

┌────────────┐
│ 031-45-154 │
└────────────┘

[7/21/2017, 2:01:42 PM] Homebridge is running on port 51826.
[7/21/2017, 2:01:42 PM] [eDomoticz] Could not register platform accessory! (WohzimmerBalkon)
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: dea24ad2-47ff-4451-9785-bcd25f2e1268
```  

The devices seem to be somehow present in homebridge but not registered?

**Comment by xTheRamon** [comment]
Could you try removing your accessories and persist folder and then re-pairing? Or is that too much of a problem? The 1.0 accessories and persist folder are not compatible with the 2.0 version.. Since the whole protocol has been updated. You'll have to re-pair though and enter the code again through the app.

**Comment by alexdie** [comment]
I did remove every file and folder except config.json before the first run. It's a completely fresh setup of homebridge. 
The second run is with the folders the first run created.

**Comment by xTheRamon** [comment]
Yeah, I'm sorry for the hassle but the folders of the first run seem corrupted.
I'm saying this because it's trying to register another device even though it is already registered.

```
[7/21/2017, 2:01:42 PM] [eDomoticz] Could not register platform accessory! (WohzimmerBalkon)
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: dea24ad2-47ff-4451-9785-bcd25f2e1268
```

I fixed this issue this morning, but the cached files can never be updated. That's why..

**Comment by alexdie** [comment]
The first run was a fresh installation of 2.0.5. 
I removed the persist and accessories folder, and it still doesn't register any devices.

**Comment by xTheRamon** [comment]
Ouch, so there must be a problem somewhere. FYI: You can always revert back to the old 'working' version: `npm install -g homebridge-edomoticz@1.0.15`

Could you output your full devices list for me please? I'll try to reproduce your case here, locally.
_Domoticz_url_ /json.htm?type=devices

**Comment by alexdie** [comment]
I already tried version 1.0.15, I had the same errors as with version 2.0.0 in the first post. 

The output of /json.htm?type=devices is this: 
```
{
   "ActTime" : 1500640301,
   "ServerTime" : "2017-07-21 14:31:41",
   "Sunrise" : "05:39",
   "Sunset" : "21:06",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "Rolladen an der Balkontüre im Wohnzimmer",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000042",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-21 09:25:59",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "WohzimmerBalkon",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ARC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "Rolladen an den Fenstern im Wohnzimmer",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000042",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-20 21:31:11",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "WohnzimmerFenster",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ARC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "2"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "Rolladen im Bad",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000042",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-21 09:26:02",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Bad",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ARC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 3,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "3"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "Rolladen im Schlafzimmer",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFLink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000042",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-21 09:25:54",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Schlafzimmer",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ARC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 4,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "4"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}
```
My homebridge config.json is this: 

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:21:3E:E4:DE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Configuration file for (e)xtended Domoticz platform.",
    "platforms": [
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "XXX.XXX.XXX.XXX",
            "port": "8080",
            "ssl": 0,
            "roomid": 0,
            "mqtt": 0
        }
    ],
    "accessories": []
}
```

**Comment by alexdie** [comment]
I've been able to install homebridge on my Macbook and the plugin works flawlessly there. This doesn't appear to be a bug in the plugin but something else with my setup. Sorry for the confusion.

I've got an entirely separate issue now, my blinds show as having a percentage state in Homekit even though I set them up as "Blinds" in Domoticz. Should I open another issue for that?

**Comment by xTheRamon** [comment]
Hmm weird! I have just tried to recreate your scenario, but everything seems to work flawlessly.

Configuration:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:21:3E:E4:DE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Configuration file for (e)xtended Domoticz platform.",
    "platforms": [
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "port": "8081",
            "ssl": 0,
            "roomid": 0,
            "mqtt": 0,
            "excludedDevices": []
        }
    ],
    "accessories": []
}
```

Logs:
```
[7/21/2017, 3:14:47 PM] Loaded plugin: homebridge-edomoticz
[7/21/2017, 3:14:47 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
[7/21/2017, 3:14:47 PM] ---
[7/21/2017, 3:14:47 PM] Loaded config.json with 0 accessories and 1 platforms.
[7/21/2017, 3:14:47 PM] ---
[7/21/2017, 3:14:47 PM] Loading 1 platforms...
[7/21/2017, 3:14:47 PM] [eDomoticz] Initializing eDomoticz platform...
[7/21/2017, 3:14:47 PM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[7/21/2017, 3:14:47 PM] Homebridge is running on port 51826.
```

App screenshot:
![img_5323](https://user-images.githubusercontent.com/18720368/28465117-f3c03966-6e27-11e7-8eab-8c61f57e21b5.jpg)

Versions:
```
$ node -v
v8.2.0
$ npm -v
5.3.0
$ homebridge --version
0.4.22
```

**Comment by xTheRamon** [comment]
Whoops! Just saw your comment. Yeah, that's a limitation of HomeKit. They know no such thing as 'open' and 'close' blinds. They all act like percentage blinds.

One thing I noticed though is that the update does not work all the time. I'll have a look at that. Normally, when you don't have percentage blinds and set it to 25% for example (under 50%), the blind should close. Anything over 50% should open them.

**Comment by alexdie** [comment]
Thanks again for your effort!

That part appears to be working for me. Setting anything above 50% sends an "open" signal, setting anything below 50% sends a "close" signal. 

I can use that to stop blinds, for example I set it to 60%, wait until it is as open as I'd like it to be, then set it to 70% and the second "open" signal stops the blind.
